### ISSUE TITLE
WORKDIR par défaut

### ISSUE THREAD

**Issue by hypsug0** [PnX-SI/GeoNature-Docker-PNX#3]
le `WORKDIR` par défaut est le répertoire utilisateur geonatadmin, vide lorsque l'on se log au conteneur. les applications GeoNature étant dans  `/geonature`. Il serait plus pertinent d'utiliser `/geonature` comme `WORKDIR` par défaut.

**Comment by camillemonchicourt** [comment]
La dockerisation de GeoNature est stabilisée depuis la version 2.12 de GeoNature dans un dépôt dédié : https://github.com/PnX-SI/GeoNature-Docker-services
