### ISSUE TITLE
Image PostGIS

### ISSUE THREAD

**Issue by hypsug0** [PnX-SI/GeoNature-Docker-PNX#4]
Il existe maintenant une image "officielle" PostGIS, a priori plus maintenue que celle de kartoza :

- registry: https://hub.docker.com/r/postgis/postgis
- source: https://github.com/postgis/docker-postgis

**Comment by camillemonchicourt** [comment]
Merci pour les tests et retours.

**Comment by ftertre** [comment]
En effet, elle sera aussi moins douteuse, (celle de kartoza sur Docker Hub ne correspondant pas toujours à ce qui devrait être décrit par le DockerFile).

Il faudra trouver le temps de tester la compatibilité (histoire d'être sur à 100% du fonctionnement).

**Comment by mathieubossaert** [comment]
Bonjour,
je vais probablement réaliser une install de geonature via docker, je pourrai tester l'image officilelle que j'utilise par ailleurs, dans ce contexte et vous faire un retour.

**Comment by mathieubossaert** [comment]
https://github.com/PnX-SI/GeoNature-docker/issues/7#issuecomment-775171661

**Comment by camillemonchicourt** [comment]
La dockerisation de GeoNature est stabilisée depuis la version 2.12 de GeoNature dans un dépôt dédié : https://github.com/PnX-SI/GeoNature-Docker-services
