### ISSUE TITLE
GeoNature-atlas optionnel

### ISSUE THREAD

**Issue by hypsug0** [PnX-SI/GeoNature-Docker-PNX#5]
L'installation de GeoNature-atlas n'est pas toujours attendue, il serait judicieux de le rendre optionnel.

Je me chargerai d'ajouter cette option si validée ;)

**Comment by camillemonchicourt** [comment]
Oui très bonne idée.

**Comment by ftertre** [comment]
Une option dans le .env serait parfaite pour ça.

**Comment by camillemonchicourt** [comment]
Dans ce dépôt spécifique GeoNature-atlas est intégré d'office.

La dockerisation générique de GeoNature est stabilisée depuis la version 2.12 de GeoNature dans un dépôt dédié : https://github.com/PnX-SI/GeoNature-Docker-services

Le fait que GeoNature-atlas y soit proposé de manière optionnelle est une évolution souhaitée : https://github.com/PnX-SI/GeoNature-Docker-services/issues/8

Sachant qu'une image Docker de GeoNature-atlas est désormais générée automatiquement à chacune de ses nouvelles versions.
