### ISSUE TITLE
GeoNature-citizen optionnel

### ISSUE THREAD

**Issue by hypsug0** [PnX-SI/GeoNature-Docker-PNX#6]
Après sortie de GeoNature-citizen V1, il serait intéressant d'ajouter optionnellement GeoNature-citizen aux applications installables

**Comment by camillemonchicourt** [comment]
Oui c'est sur que ça serait idéal.

**Comment by camillemonchicourt** [comment]
Oui intéressant, comme GeoNature-atlas, à faire plutôt dans le dépôt générique de dockerisation de GeoNature : https://github.com/PnX-SI/GeoNature-Docker-services
